@extends(config('laravelveso.printing'))
@section('content') 
<table class='printing'>
    <tr>
        @for($i=0;$i<$numberPrint/2;$i++)
            <td>
            @include('laravelveso::printing.component.mega645') 
            </td>
        @endfor
    <tr>
    @if($numberPrint>1)
    <tr>
        @for($i=0;$i<$numberPrint/2;$i++)
            <td>
            @include('laravelveso::printing.component.mega645') 
            </td>
        @endfor
    <tr>
    @endif
</table> 
@include('laravelveso::printing.component.styles'.$numberPrint.'.mega645') 
<script>
     window.print();
</script>
@endsection